### ISSUE TITLE
Build recipe in  "Tasks starting..." loop.

### ISSUE THREAD

**Issue by EzEmbedded** [crops/toaster-container#32]
I'm building recipe with toaster-container .
My host  os is ubuntu18.
**scanlidocker/toaster-container:hardknott** is my lasted docker image build with github actions from crops/toaster-container "https://github.com/EzEmbedded/yocto-container".
My start cmd is 
`docker run -it --rm -p 0.0.0.0:18000:8000 -v /home/toaster-container:/workdir scanlidocker/toaster-container:hardknott`

```
### Shell environment set up for builds. ###

You can now run 'bitbake <target>'

Common targets are:
    core-image-minimal
    core-image-full-cmdline
    core-image-sato
    core-image-weston
    meta-toolchain
    meta-ide-support

You can also run generated qemu images with a command like 'runqemu qemux86'

Other commonly useful commands are:
 - 'devtool' and 'recipetool' handle common recipe tasks
 - 'bitbake-layers' handles common layer tasks
 - 'oe-pkgdata-util' handles common target package tasks
The system will start.
Check if toaster can listen on 0.0.0.0:8000
OK
kill: (115): No such process
Operations to perform:
  Apply all migrations: admin, auth, bldcontrol, contenttypes, orm, sessions
Running migrations:
  No migrations to apply.
Starting webserver...
Toaster development webserver started at http://0.0.0.0:8000

You can now run 'bitbake <target>' on the command line and monitor your build in Toaster.
You can also use a Toaster project to configure and run a build.

Successful start.
```
when I  ran **bitbake  core-image-minimal**  in CLI It  succeed.
when I build **bitbake  core-image-minimal** on web, it runs into  "Tasks starting..." loop .
toaster_ui.log is:
```
Traceback (most recent call last):
  File "/home/usersetup/poky/bitbake/bin/bitbake", line 36, in <module>
    cookerdata.CookerConfiguration()))
  File "/home/usersetup/poky/bitbake/lib/bb/main.py", line 367, in bitbake_main
    server_connection, ui_module = setup_bitbake(configParams)
  File "/home/usersetup/poky/bitbake/lib/bb/main.py", line 423, in setup_bitbake
    configParams.observe_only, configParams.xmlrpctoken)
  File "/home/usersetup/poky/bitbake/lib/bb/server/xmlrpcclient.py", line 138, in connectXMLRPC
    raise e
  File "/home/usersetup/poky/bitbake/lib/bb/server/xmlrpcclient.py", line 134, in connectXMLRPC
    connection = BitBakeXMLRPCServerConnection(host, port, (ip, 0), observer_only, featureset)
  File "/home/usersetup/poky/bitbake/lib/bb/server/xmlrpcclient.py", line 76, in __init__
    self.events = uievent.BBUIEventQueue(self.connection, self.clientinfo)
  File "/home/usersetup/poky/bitbake/lib/bb/ui/uievent.py", line 45, in __init__
    ret = self.BBServer.registerEventHandler(self.host, self.port)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<class 'AttributeError'>:module 'bb.server' has no attribute 'xmlrpcclient'">
WARNING: Could not connect to server at 0.0.0.0:43815 (<Fault 1: "<class 'AttributeError'>:module 'bb.server' has no attribute 'xmlrpcclient'">)
```

**Comment by moto-timo** [comment]
This turns out to be a bug in bitbake itself (not Toaster specific):
https://bugzilla.yoctoproject.org/show_bug.cgi?id=14753

**Comment by moto-timo** [comment]
This has been resolved in kirkstone/master.

**Comment by moto-timo** [comment]
This will come up from time to time when upstream bitbake breaks us, but now that Toaster tests have been re-enabled in bitbake itself (yocto-4.3+) we do not expect to see this recur. 
https://git.openembedded.org/bitbake/log/lib/toaster/tests?h=yocto-4.3

Running the refreshed tests on the AutoBuilder is currently work-in-progress, but expect it to be run regularly by the end of the year (December 2023).
https://autobuilder.yoctoproject.org/typhoon/#/builders/161
